//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDouWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_List
    {
        public int MusicID { get; set; }
        public string MusicName { get; set; }
        public int TypeID { get; set; }
        public int SingerID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public int Status { get; set; }
    
        public virtual Music_Singer Music_Singer { get; set; }
        public virtual Music_Type Music_Type { get; set; }
    }
}
