//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDouWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music_Type()
        {
            this.Music_List = new HashSet<Music_List>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Music_List> Music_List { get; set; }
    }
}
